# Generated by Django 6.0.1 on 2026-03-31 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PortfolioPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("headline", models.CharField(max_length=255)),
                ("hero_badge", models.CharField(max_length=255)),
                ("hero_description", models.TextField()),
                ("about_text", models.TextField()),
                ("contact_title", models.CharField(max_length=255)),
                ("contact_description", models.TextField()),
                ("location", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=50)),
                ("github_label", models.CharField(blank=True, max_length=120)),
                ("github_url", models.URLField(blank=True)),
                (
                    "cv_filename",
                    models.CharField(default="Achiek_Deng_CV.pdf", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Portfolio Page",
                "verbose_name_plural": "Portfolio Page",
            },
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("value", models.CharField(max_length=40)),
                ("label", models.CharField(max_length=160)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="siteapp.portfoliopage",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FocusArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("label", models.CharField(max_length=120)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="focus_areas",
                        to="siteapp.portfoliopage",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExperienceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("role", models.CharField(max_length=200)),
                ("organization", models.CharField(blank=True, max_length=200)),
                ("period", models.CharField(max_length=80)),
                ("description", models.TextField()),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experience_items",
                        to="siteapp.portfoliopage",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EducationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=200)),
                ("organization", models.CharField(max_length=200)),
                ("period", models.CharField(max_length=80)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_items",
                        to="siteapp.portfoliopage",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CertificationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=200)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certification_items",
                        to="siteapp.portfoliopage",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=200)),
                ("category", models.CharField(blank=True, max_length=160)),
                ("period", models.CharField(max_length=80)),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("award", "Award"),
                            ("bar-chart-3", "Bar Chart"),
                            ("briefcase", "Briefcase"),
                            ("camera", "Camera"),
                            ("code-2", "Code"),
                            ("cpu", "CPU"),
                            ("globe", "Globe"),
                        ],
                        max_length=40,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="siteapp.portfoliopage",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("text", models.CharField(max_length=255)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlights",
                        to="siteapp.project",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectStackItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("label", models.CharField(max_length=120)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stack_items",
                        to="siteapp.project",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=160)),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("award", "Award"),
                            ("bar-chart-3", "Bar Chart"),
                            ("briefcase", "Briefcase"),
                            ("camera", "Camera"),
                            ("code-2", "Code"),
                            ("cpu", "CPU"),
                            ("globe", "Globe"),
                        ],
                        max_length=40,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="siteapp.portfoliopage",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Skill categories",
                "ordering": ["position", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SkillEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("label", models.CharField(max_length=120)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="siteapp.skillcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Strength",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField()),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strengths",
                        to="siteapp.portfoliopage",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
                "abstract": False,
            },
        ),
    ]
