# Generated by Django 6.0.1 on 2026-03-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfoliopage",
            name="about_eyebrow",
            field=models.CharField(default="About", max_length=80),
        ),
        migrations.AddField(
            model_name="portfoliopage",
            name="about_title",
            field=models.CharField(default="Professional Profile", max_length=200),
        ),
        migrations.AddField(
            model_name="portfoliopage",
            name="certifications_title",
            field=models.CharField(default="Certifications", max_length=200),
        ),
        migrations.AddField(
            model_name="portfoliopage",
            name="contact_eyebrow",
            field=models.CharField(default="Contact", max_length=80),
        ),
        migrations.AddField(
            model_name="portfoliopage",
            name="education_title",
            field=models.CharField(default="Education", max_length=200),
        ),
        migrations.AddField(
            model_name="portfoliopage",
            name="experience_title",
            field=models.CharField(default="Experience", max_length=200),
        ),
        migrations.AddField(
            model_name="portfoliopage",
            name="projects_eyebrow",
            field=models.CharField(default="Projects", max_length=80),
        ),
        migrations.AddField(
            model_name="portfoliopage",
            name="projects_title",
            field=models.CharField(default="Selected Work", max_length=200),
        ),
        migrations.AddField(
            model_name="portfoliopage",
            name="skills_eyebrow",
            field=models.CharField(default="Skills", max_length=80),
        ),
        migrations.AddField(
            model_name="portfoliopage",
            name="skills_title",
            field=models.CharField(default="Technical Capabilities", max_length=200),
        ),
    ]
