# Generated by Django 6.0.1 on 2026-03-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteapp", "0002_portfoliopage_about_eyebrow_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
