# Generated by Django 6.0.3 on 2026-03-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteapp", "0003_project_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfoliopage",
            name="linkedin_label",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="portfoliopage",
            name="linkedin_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
