# Generated by Django 6.0.3 on 2026-03-31 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteapp", "0004_portfoliopage_linkedin_label_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("linkedin", "LinkedIn"),
                            ("instagram", "Instagram"),
                            ("x", "X"),
                            ("facebook", "Facebook"),
                            ("youtube", "YouTube"),
                            ("behance", "Behance"),
                            ("dribbble", "Dribbble"),
                            ("globe", "Website"),
                        ],
                        default="globe",
                        max_length=40,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=120)),
                ("url", models.URLField()),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="siteapp.portfoliopage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social link",
                "verbose_name_plural": "Social links",
                "ordering": ["position", "id"],
                "abstract": False,
            },
        ),
    ]
